### ISSUE TITLE
Access to API?

### ISSUE THREAD

**Issue by Spone** [iZettle/api-documentation#2]
Hello there,
I'd like to integrate iZettle with our custom inventory / accounting tool, so I would need a basic read access to our iZettle account balance and purchases.
How can I apply for an API key?
Thanks in advance.

**Comment by Joosha** [comment]
Hi,

First of all I'm sorry for the really delayed respons but we don't use this repo for issue tracking or communication. We only use it as a temporary documentation so we don't watch it for incoming issues.

Our API, and this documentation, is work in progress and right now we only give access to a select few. If you are still interested in early access I suggest reaching out to partnerships@izettle.com with your case and we'll take it from there.

Best regards
