### ISSUE TITLE
I want to apply as a partner

### ISSUE THREAD

**Issue by onklmaps** [iZettle/api-documentation#20]

**Comment by Joosha** [comment]
Hi,

First of all I'm sorry for the delayed respons but we don't use this repo for issue tracking or communication. We only use it as a temporary documentation so we don't watch it for incoming issues.

Our API, and this documentation, is work in progress and not open for everyone yet. If you are still interested in access I suggest reaching out to api@izettle.com with your case and we'll take it from there.

Best regards
