### ISSUE TITLE
Provide more information about the payment types

### ISSUE THREAD

**Issue by LauLaman** [iZettle/api-documentation#30]
As for the [Purchase API V1](https://github.com/iZettle/api-documentation/blob/master/purchase.adoc) and [Purchase API V2](https://github.com/iZettle/api-documentation/blob/master/purchase_v2.adoc) documentation

There is no information regarding the following Payment types:
- [ ] IZETTLE_INVOICE
- [x] MOBILE_PAY
- [x] SWISH
- [x] VIPPS

Can you provide me with the structure the API will return?
Like you did for the `IZETTLE_CARD` type:
```json
{
  "uuid": "165b88a0-07a3-11e6-9dae-43c30f1bff5b",
  "amount": 2000,
  "type": "IZETTLE_CARD",
  "attributes": {
    "transactionStatusInformation": "EC00",
    "cardPaymentEntryMode": "EMV",
    "maskedPan": "476173******0119",
    "installmentAmount": null,
    "referenceNumber": "AU54FYHW7X",
    "nrOfInstallments": 0,
    "cardType": "VISA",
    "terminalVerificationResults": "0080088000",
    "applicationIdentifier": "A0000000031010",
    "applicationName": "Visa Credit"
  }
}
```

**Comment by Sarastro72** [comment]
Hi,

For all but `IZETTLE_INVOICE` the attributes will be empty. There will only be ùuid`, `amount` and `type`.

I will come back with the Invoice case, there is probably a reference number in the attributes. BRB.

**Comment by Sarastro72** [comment]
The Invoice can have three attributes as follows

```
"payments": [
                {
                    "uuid": "d65ebf50-979e-11e7-9f72-df4bb64e0df9",
                    "amount": 2960,
                    "type": "IZETTLE_INVOICE",
                    "attributes": {
                        "orderUUID": "d5b126c4-979e-11e7-9af0-a3d2806c42a1",
                        "invoiceNr": "iz37",
                        "dueDate": "2017-10-12"
                    }
                }
            ]
```

I hope this answers your questions, otherwise reopen this issue.
