### ISSUE TITLE
Request: Always return Money object.

### ISSUE THREAD

**Issue by LauLaman** [iZettle/api-documentation#33]
I think its good practice to always return a money object instead of an int. If we always return an money object its much harder to lose the context.

**Example**
When requesting the [AccountTransactions](https://github.com/LauLamanApps/iZettleApi/blob/master/tests/Integration/Client/files/FinanceClient/getAccountTransactions.json) the amount is only an `int` and from this `int` only, we cannot tell the currency, so we are missing the context of the amount.  Especially in [this](https://finance.izettle.com/swagger#!/accounts/getAccountTransactions) API call, the currency is never defined.

If you guys change this like this everything is clear immediately: (and also make it inline with  [Fowler's Money pattern](https://martinfowler.com/eaaCatalog/money.html))
```json
{
  "data": [
    {
      "timestamp": "2017-11-03T22:59:17.162+0000",
      "amount": {
        "amount": -4,
        "currency": "EUR"
      },
      "originatorTransactionType": "CARD_PAYMENT_FEE",
      "originatingTransactionUuid": "713e7b0e-c4d7-11e7-abc4-cec278b6b50a"
    },
    {
      "timestamp": "2017-11-03T22:59:17.162+0000",
      "amount": {
        "amount": 150,
        "currency": "EUR"
      },
      "originatorTransactionType": "CARD_PAYMENT",
      "originatingTransactionUuid": "713e7b0e-c4d7-11e7-abc4-cec278b6b50a"
    }
  ]
}
```
Maybe the `amount` node on `amount` is not very nice but I think you'll get the idea.

**Comment by adamvoncorswant** [comment]
Hey @LauLaman ! Thank you for the suggestion! Yes, this is probably a good idea (if nothing else for clarity). The thing is that the way some of our systems are built, they are not even aware of the currency (as it's irrelevant for the actual business logic, and a given customer can only ever have one currency in our systems). This makes it non-trivial to make this change as per your suggestion.

Perhaps someday in the future though!
