### ISSUE TITLE
OAuth at SwaggerUI doesn't work

### ISSUE THREAD

**Issue by punk2000** [iZettle/api-documentation#38]
When trying to test your API with Swagger (https://products.izettle.com/swagger#/products/createProduct) the Authorize option doesn't work and leads into a 404 in your side:

https://oauth.izettle.net/?response_type=token&client_id={client_id}&redirect_uri=%2Foauth2-redirect.html&scope=READ%3APRODUCT%20WRITE%3APRODUCT&state=TW9uIEZlYiAxMiAyMDE4IDIyOjU2OjA0IEdNVCswMTAw&realm=your-realms

**Comment by martinfridh** [comment]
@punk2000 sorry for late feedback on this, though if you have questions that are not answered in the FAQ document at https://github.com/iZettle/api-documentation/blob/master/faq.adoc please use our api-team email address: api@izettle.com
