### ISSUE TITLE
Authorization code is not invalidated after use

### ISSUE THREAD

**Issue by alexanderzinolidis** [iZettle/api-documentation#39]
It seems like the oAuth service doesn't invalidate auth codes after they have been used. They do expire, but according to RFC 6749 (https://tools.ietf.org/html/rfc6749#section-4.1.2) it must not be possible to request new tokens from an already used authorization code.

Is this by design for some reason? It makes it easier for our integration for sure, but might be worth looking at.

**Comment by martinfridh** [comment]
sorry for late feedback on this, though if you have questions that are not answered in the FAQ document at https://github.com/iZettle/api-documentation/blob/master/faq.adoc please use our api-team email address: api@izettle.com
