### ISSUE TITLE
Expected format for date?

### ISSUE THREAD

**Issue by Spone** [iZettle/api-documentation#42]
Hello,

can you add to the documentation the expected format for dates? For instance `startDate` and `endDate` for the [Purchases](https://github.com/iZettle/api-documentation/blob/master/purchase.adoc#get-purchase-history).

Thank you

**Comment by Spone** [comment]
It seems to be `YYYY-MM-DD` (`2018-03-13`)

**Comment by martinfridh** [comment]
@Spone sorry for late feedback on this, though if you have questions that are not answered in the FAQ document at https://github.com/iZettle/api-documentation/blob/master/faq.adoc please use our api-team email address: api@izettle.com
