### ISSUE TITLE
KeyNotFoundException: Key xyz was not found in authorization service.

### ISSUE THREAD

**Issue by Kaily** [iZettle/api-documentation#43]
Hi, while creating any product I am receiving following error,

{
    "developerMessage": "KeyNotFoundException: Key 1521547091191 was not found in authorization service",
    "errorType": "INTERNAL_SERVER_ERROR",
    "violations": []
}

I am passing valid bearer token in authorization header.

**Comment by alexanderzinolidis** [comment]
Hi Kaily,

I don't work for iZettle but i'll try to assist you. How does your request body look? Specifically the Authorization header, are you passing "1521547091191" as your bearer token?

**Comment by Kaily** [comment]
Hi Alexander,

**Comment by Kaily** [comment]
Hi Alexanderzinolidis,
Thanks for your response. I checked my token , I decoded it and found following data

{"kid":"1521547091191","typ":"JWT","alg":"RS256"}

So yes, it means, I am passing this value.

**Comment by alexanderzinolidis** [comment]
@Kaily Have a look at how the requests should look:

curl -X GET \
  https://products.izettle.com/organizations/self/library \
  -H 'Authorization: Bearer eyJraWQiOxxxxxDkxMTkxIiwidHlwIjoiSldUIiwiYWxnIjoiUlMyNTYifQ.eyJpxxxxxxlIiwiYXVkIjoiQVBJIiwiZXhwIjoxNTIxNTkxNDIxLCJzdWIiOiIwNTQyYjI5MC05MjIyLTExZTctYTg1MS0zYWE3MzQzZjU1NTkiLCJzY29wZSI6WyJSRUFExxxxJ[REDACTED]NFIiwiUkVBRDpVU0VSSU5GTyIs[REDACTED]TkFOQ0UiLCJXUklURTpQUk9EVUNUIiwiV1JJVEU6UFVSQ0hBU0UiLCJXUklURTpVU0VSSU5GTyJdLCJ1c2VyIjp7InVzZXJUeXBlIjoiVVNFUiIsInV1aWQiOiIwN[REDACTED]TctYTg1MS0zYWE3MzQxxxxxdWlkIjoiMDU0MGRkZDAtOTIyMi0xMWU3LWExYzItMWY0Oxxx0ZjdhIiwidXNlclJvbGUiOiJPV05FUiJ9LCJjbGllbnRfaWQiOiI4M2Y4[REDACTED]kMWUtOWRjNC02NmYwMGYxYmQzMDkifQ.RSE3xMxZci77rldjrZGev_bPvc1NG53HgduupLitmEpOI7W_5cH9TWWypgfDCC-kDYZXhxxxxUhGQNydYucn0t5wYrHINjulS1LnbJqGFEyN5nbiLH6S8ZxxxxGvBLScsyH6FaTDCyoabgwLvpJtJ0HG__ODtO7RJhDj4GOCb7Ttkxxxxx1DfnRdb6YbvTvS4Y5xkRoj3BqTKJbQBUQzlnMzxvc51L3ApxxxxxlOAnOBU0A2XuXdWvjM-4EU7G8OaHp_MndNZ3T1qfOeNRce0_Jwf6oBh1pabs3agjWdQY3TKo2vBVzKIDXw' \
  -H 'Content-Type: application/json'

You are probably sending your requests like this already, but this works perfectly for me. Which endpoint are you trying to reach? Do all of them return the same error?

**Comment by Kaily** [comment]
GET is working perfectly. But this error is occurring while I am using POST and trying to insert data.

**Comment by alexanderzinolidis** [comment]
@Kaily That is strange. Did you try to fully rotate the codes? I.e. do the whole oAuth flow from the beginning.

Which endpoint are you trying to POST to? I can try and see if it works for me.

**Comment by Kaily** [comment]
Hi @alexanderzinolidis,
Thanks for you response and time. Actually I was using test end point, so it was giving error.
Problem solved.

**Comment by alexanderzinolidis** [comment]
Hi @Kaily, glad to hear that! 🙂
