### ISSUE TITLE
fromEventLogUuid is null

### ISSUE THREAD

**Issue by torkiljohnsen** [iZettle/api-documentation#44]
When getting the library, it says in the docs that `fromEventLogUuid` should be a string, and I would expect it to be a UUID.

![image](https://user-images.githubusercontent.com/318089/38868242-af0d25ec-4246-11e8-9a4d-ee016dbe9a86.png)

But when calling the endpoint, the value is actually `null`. 

The return data I get is something like this:

```js
{
    "untilEventLogUuid":"945eb480-4233-11e8-872a-73e6dfd45eb4",
    "fromEventLogUuid":null,
    "products":[
		{
			"uuid":"4fa03a80-936c-11e5-a0be-5cd6168eb23a",
			"categories":[],
			"name":"Tskjorte",…
```

This caused a problem for me when testing the [unofficial PHP implementation](https://github.com/LauLamanApps/iZettleApi/) as it assumes that this value is a UUID.

Is there something I'm missing here? Is the `null` value perhaps unexpected?

**Comment by torkiljohnsen** [comment]
See issue reported here: https://github.com/LauLamanApps/iZettleApi/issues/18

**Comment by LauLaman** [comment]
This can be closed. issue resolved in the ApiClient
