### ISSUE TITLE
Hello?

### ISSUE THREAD

**Issue by andreaslarssen** [iZettle/api-documentation#46]
Hi.

I've emailed both api@izettle.com and integrations@izettle.com over a month ago, but still haven't heard anything. Also, when calling you, I'm told to email GitHub my questions about your API. Seems like you need to update your support team on how the API and GitHub works.

If you're not answering emails, are there anyone reading these issues? I see a comment on one of the other issues saying that you're not, and that I should email api@izettle.com.

I need some direction on how to export daily settlement vouchers from iZettle.

**Comment by alexanderzinolidis** [comment]
Hi @andreaslarssen,

That's unfortunate, but I might be able to assist. Do you have any specific questions?

**Comment by andreaslarssen** [comment]
Hi, thanks.

I want to export daily settlement vouchers from iZettle, and after reading the docs, I've reached the conclusion that it's the finance API I'm looking for.

To begin with, I'm just wondering if it sounds like I've read the docs right.

Also, I've read somewhere that they don't offer a test account, and was wondering if it's possible to create an account with test data myself.
