### ISSUE TITLE
Issue with payments

### ISSUE THREAD

**Issue by spilin** [iZettle/api-documentation#47]
I use your `/purchases` endpoint, and recently every first requests on that endpoint returns 
`"{\"code\":500,\"message\":\"There was an error processing your request. It has been logged (ID 04ffb32b229d7a80).\"}"` If I repeat that same request in few seconds, it usually gets through.. It might have something to do with amount of data that I'm extracting.. Can you take a look at this please?

**Comment by martinfridh** [comment]
@spilin sorry for late feedback on this, though if you have questions that are not answered in the FAQ document at https://github.com/iZettle/api-documentation/blob/master/faq.adoc please use our api-team email address: api@izettle.com
