### ISSUE TITLE
503 Service temporarily unavailable

### ISSUE THREAD

**Issue by DaviddeRijke** [iZettle/api-documentation#48]
Hi,

I'm getting a '503 Service temporarily unavailable' when trying to reach the inventory API (I do have a valid token)
Does anyone know if the problem is on my side, or if there is an issue at iZettle's?

Thanks :)

**Comment by martinfridh** [comment]
@DaviddeRijke sorry for late feedback on this, though if you have questions that are not answered in the FAQ document at https://github.com/iZettle/api-documentation/blob/master/faq.adoc please use our api-team email address: api@izettle.com
