### ISSUE TITLE
Organisation endpoint?

### ISSUE THREAD

**Issue by stevenjfr** [iZettle/api-documentation#58]
Is it possible to add an endpoint for returning details about my organisation such as address, etc etc. if it doesn't already exist?

**Comment by alexander7161** [comment]
I’m wondering the same thing

**Comment by daniel-mur** [comment]
Same, need to get info from my organisation.

**Comment by martinfridh** [comment]
@stevenjfr @alexander7161 @daniel-mur sorry for late feedback on this, though if you have questions that are not answered in the FAQ document at https://github.com/iZettle/api-documentation/blob/master/faq.adoc please use our api-team email address: api@izettle.com
