### ISSUE TITLE
Incorrect dates in "purchase"

### ISSUE THREAD

**Issue by obedramales** [iZettle/api-documentation#59]
Hello, I have a problem with the api.
I use the route "purchase" and get the data per day, but I found that there are purchases that are made for example today, and when the request is made today do not appear, appear on the next day and is the date of purchase.

thank you

**Comment by martinfridh** [comment]
@obedramales sorry for late response on this, though if you have questions that are not answered in the FAQ document at https://github.com/iZettle/api-documentation/blob/master/faq.adoc please use our api-team email address: api@izettle.com
