### ISSUE TITLE
Print tickets only one time

### ISSUE THREAD

**Issue by GasparFD** [iZettle/api-documentation#60]
Is it possible to print the tickets only one time?
In izettle -> Sales -> Tickets you can print the tickes again. We want to block this funtion.
We are a bus company and we use izettle to sell our bus tickets, but the driver can to print a ticket one time and again.
Can you help us?

**Comment by martinfridh** [comment]
@GasparFD sorry for late response on this, though if you have questions that are not answered in the FAQ document at https://github.com/iZettle/api-documentation/blob/master/faq.adoc please use our api-team email address: api@izettle.com
