### ISSUE TITLE
Error when trying to create a refund

### ISSUE THREAD

**Issue by jlarrubiaq** [iZettle/api-documentation#62]
Hi,

when trying to create a refund via API (https://purchase.izettle.com/purchase/v2/refund) I always get this 

error:
 "errors": [
        "shoppingCartUUID may not be null",
        "uuid may not be null"
    ]

But I can't find any reference in the docs mentioning them. Any idea?

Thanks

**Comment by martinfridh** [comment]
@jlarrubiaq Sorry for late response in this, but if you have questions that are not answered in the FAQ document at https://github.com/iZettle/api-documentation/blob/master/faq.adoc please use our api-team email address: api@izettle.com
