### ISSUE TITLE
Product amount is wrong in documentation

### ISSUE THREAD

**Issue by LinTicket** [iZettle/api-documentation#66]
In documentation example, amount is shown as "5" and currency ID as "SEK".
It appears the amount should be in "øre" and not "kroner" when using currency ID "NOK".
The amount "5" would show up as 0,05 in the product list and not 5,00 as expected.

**Comment by williamboman** [comment]
Hi! Thanks for raising an issue. Where do you get the information that `5.00 SEK` is the expected amount for the product in the documentation?

**Comment by LinTicket** [comment]
I see there's additional documentation hidden in the swagger part that mentions this, so this issue can ble closed. You might consider improving the examples with some more comments/text, though ...
