### ISSUE TITLE
purchases/v2 not showing all purchases(i.e. IZETTLE_CASH) 

### ISSUE THREAD

**Issue by radolan71** [iZettle/api-documentation#68]
I am using the https://purchase.izettle.com/purchases/v2 endpoint to retrieve purchases from a Mexican merchant. However the response is not including cash purchases which is the other payment method they are currenlty using. 

I can see those purchases in your backoffice (https://backoffice.intelligentpos.com) but not in the api response.

Let me know if you need futher details to debug this issue.

Regards

Eduardo

**Comment by williamboman** [comment]
Hi Eduardo,

If you're using iZettle Pro you will only see purchases made with cards through the iZettle Go APIs (which the Purchase API is part of). If you'd like access to the iZettle Pro APIs please send an email to api@izettle.com.
