### ISSUE TITLE
Products not removed from list in app after removing in API

### ISSUE THREAD

**Issue by LinTicket** [iZettle/api-documentation#69]
I have tried to contact api@izettle.com and support@izettle.com with no response for a month, therefore I will try here.

It seems some products in the Go app are not removed when removed from the products list.

See attached screenshots of product list from web page and from Go app.

Is this expected behavior ?

How does one achieve synchronization between the Go app and the products list ?

![Screenshot from 2019-07-01 11-05-43](https://user-images.githubusercontent.com/6075147/62555844-f43e8a80-b873-11e9-840d-6c0563d7fc80.png)
![Screenshot_20190701-110539_iZettle Go](https://user-images.githubusercontent.com/6075147/62555845-f4d72100-b873-11e9-87fc-202c5eb739de.jpg)

**Comment by martinfridh** [comment]
@LinTicket sorry for late feedback on this, though if you have questions that are not answered in the FAQ document at https://github.com/iZettle/api-documentation/blob/master/faq.adoc please use our api-team email address: api@izettle.com
