### ISSUE TITLE
Clarify authorization doesn't use developer username and password

### ISSUE THREAD

**Issue by cowlingj** [iZettle/api-documentation#82]
I'm new to iZettle and want to see what I can do with it because I have a client already using iZettle products. I got started by creating a developer account, created my first private integration (just as a "hello world" kind of thing to play about with the APIs) and I then got pointed towards the docs.
First things first I wanted to make sure I could authenticate, but this is where I struggled because I couldn't get a token with my username and password.
I was unaware of the difference between an iZettle username and password and my developer username and password (because I was just interested in what API's were on offer, I didn't realise that the credentials for the account I just created were not the ones required for authentication).

I think it could be useful further clarifying that the developer credentials are not the ones required for authentication, perhaps a note in the [request an access token](https://github.com/iZettle/api-documentation/blob/master/authorization.adoc#request-an-access-token) section, after the example cURL request like
> You need to use your username and password for your iZettle account, not your developer account, if you don't have one, you can create an iZettle account [here](https://register.izettle.com)
Obviously the exact wording is less important than the distinction between developer account and iZettle account.

Maybe I'm in the minority, not realising that when I signed up as an iZettle developer, that I still needed a separate iZettle account. but I think there's little harm in adding the clarifying note to the docs.

**Comment by Frodo1980** [comment]
This was not my problem, but I agree to the point, that the documentation could be a little more detailled. Code-Snipplets for easy integration would be great!!

**Comment by martinfridh** [comment]
thank you for you feedback @cowlingj ! In case if you have any other questions or feedback, please use our api-team email address: api@izettle.com
