### ISSUE TITLE
CORS / Password grant

### ISSUE THREAD

**Issue by Frodo1980** [iZettle/api-documentation#83]
Hi,

sorry, didn't find anything in FAQ, so hopefully I will get some help here.

Doing the authorization-API-call via password grant in postman everything works fine.

Trying to do the same by my website in visual studio code / Live server (XMLhttprequest) I get CORS-error:

`Access to XMLHttpRequest at 'https://oauth.izettle.com/token/grant_type=password&client_id=75a9fde1-085d-4dac-999e-13055d626dd2&client_secret=IZSEC38fb666a-0cf2-4cd7-8ac2-2a4ba41da08c&username=*****&password=*****' from origin 'http://127.0.0.1:5500' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

Any hint? Thanks!!

Michael

**Comment by martinfridh** [comment]
@Frodo1980 if you have questions that are not answered in the FAQ document at https://github.com/iZettle/api-documentation/blob/master/faq.adoc please use our api-team email address: api@izettle.com
