### ISSUE TITLE
API access

### ISSUE THREAD

**Issue by paneq** [iZettle/api-documentation#9]
Hello there,

I'd like to integrate iZettle with our reconciliation process, so I would need an access to the API. Please provide me with a secret and client id (mentioned here https://github.com/iZettle/api-documentation/blob/master/authorization.adoc#ask-the-user-to-authorize-the-client ) over an email to `robert.pankowecki@arkency.com`.

**Comment by tmus** [comment]
Hey @paneq, I'm in the same boat, but the impression I got from this repo is that it is a work in progress? If that's right, is there any timeline for completion? This looks very exciting.

If that's not the case guys, I'd like a set of credentials, too! :smile:

**Comment by Joosha** [comment]
Hi,

We are thrilled that you are interested in iZettle's API. The API, and this documentation, is work in progress and right now we only grant access to a select few partners. 

There are plans to make more of the API available to a broader audience but unfortunately we cannot share specifics at this time. However, your interest in our API have been noted and will be taken into consideration when we are prioritising our upcoming work.

If you are interested in early access I suggest reaching out to partnerships@izettle.com with your case and we'll take it from there. I just want to make it clear that early access is not guaranteed.

Best regards
